# Generated by Django 6.0 on 2026-01-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
