# Generated by Django 6.0 on 2026-01-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanger', '0002_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(choices=[('tops', 'トップス'), ('pants', 'パンツ'), ('outer', 'アウター'), ('shoes', 'シューズ'), ('accessories', 'アクセサリー'), ('others', 'その他')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('season', models.CharField(choices=[('spring', 'spring'), ('summer', 'summer'), ('autumn', 'autumn'), ('winter', 'winter')], max_length=100)),
                ('items', models.ManyToManyField(to='hanger.item')),
            ],
        ),
        migrations.DeleteModel(
            name='Clothes',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
