# Generated by Django 6.0 on 2026-01-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanger', '0003_item_outfit_delete_clothes_delete_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
