# Generated by Django 6.0 on 2026-02-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanger', '0004_item_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('トップス', 'トップス'), ('パンツ', 'パンツ'), ('アウター', 'アウター'), ('シューズ', 'シューズ'), ('アクセサリー', 'アクセサリー'), ('その他', 'その他')], max_length=100),
        ),
    ]
