# Generated by Django 6.0 on 2026-02-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanger', '0005_alter_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='season',
        ),
        migrations.AddField(
            model_name='outfit',
            name='season',
            field=models.ManyToManyField(to='hanger.season'),
        ),
    ]
