# Generated by Django 6.0 on 2026-02-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanger', '0006_season_remove_outfit_season_outfit_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='season',
        ),
        migrations.AddField(
            model_name='outfit',
            name='seasons',
            field=models.ManyToManyField(to='hanger.season'),
        ),
    ]
